---
title: "Academic and Professional Experience"
---
***

## Credentials and Education

#### Degrees                      

* PhD in Environmental Health Sciences, Environmental Epidemiology  
Mailman School of Public Health, Columbia University, New York, NY  
2018-present

*	Master of Public Health, Epidemiology  
	College of Global Public Health, New York University, New York, NY  
	2014-2017  
	**Thesis:** Childhood Cancer and Exposure to Industry: An Ecologic Study of New Jersey Counties Using Data from the Toxic Release Inventory

* Bachelor of Arts, English  
Regis University, Denver, CO  
2007-2011  
**Thesis:** Living in the Mystery: Myriad Approaches to Death in Edgar Allan Poe’s Tales of Terror

#### Certifications		

* Standard Certificate, Teacher of English, New Jersey  
Cert #907813

<br>

## Public Health Experience

* **Project Manager, Departments of Pediatrics and Population Health**  
PIs: Michael Weitzman MD, Scott Sherman MD, Terry Gordon PhD  
NYU Langone Medical Center, New York, NY  
5/2015 - 8/2017
    + Promoted from Project Coordinator to Project Manager after 18 months
    + Managed a variety of public health research projects, domestically and globally, including the administration and submission of grants, IRB applications and compliance, creation of data collection tools, study design and implementation, management of data collection and research staff, and analysis of large nationally representative datasets
    + **Domestic projects:**  
    Smoking Cessation and the Oral Microbiome  
    Air Quality, Child, and Adult Health in Homes where Hookahs and E-cigarettes are Used  
    Air Quality in Vape Shops  
    CUNY Tobacco & Health Behavior Survey  
    Survey of Knowledge and Beliefs of Alternative Tobacco Products among Dental Students  
    Indoor Air Quality in Homes of Hookah Smokers and E-cigarette Users  
    Dental and Periodontal Disease and Hookah Smoking (New York City)
    + **Global projects:**  
    Abu Dhabi Cohort Study, Abu Dhabi, UAE  
    Periodontal Disease and Hookah Smoking, Sharjah, UAE  
    Quit Buddy App for Smoking Cessation, NYU/St. Petersburg, Russia

###

* **Intern, US Environmental Protection Agency, Region II**  
Office of the Regional Administrator, Special Projects, New York, NY  
05/2017-09/2017	
    + Interviewed numerous stakeholders throughout Region II involved with reducing childhood exposure to lead paint, including representatives of local governments, non-governmental organizations, universities, and public health offices
    + Developed a resource for community coalitions to use when working to reduce primary lead exposure in their regions

###

* **Research Assistant, Department of Pediatrics**  
NYU Langone Medical Center, New York, NY  
PI: Michael Weitzman MD  
11/2014 - 5/2015
    + Analyzed data using Stata from the Global Adult Tobacco Survey, in conjunction with colleagues, to evaluate worldwide tobacco cessation resource use
    + Collaborated with team of students to develop a masters level course on licit and illicit drug use titled Drug Use in Public Health, including the design and production of all materials and assignments
    + Served as teaching assistant for the course *Drug Use in Public Health* for two semesters

<br>

## Select Publications

1.  [Effects of hookah smoking on indoor air quality.](https://www.ncbi.nlm.nih.gov/pubmed/27798320)

2.  [Parental Psychological Distress and Food Insecurity: Sad Dads in Hungry Homes.](https://www.ncbi.nlm.nih.gov/pubmed/28742541)

3.  [Dental, Dental Hygiene, and Advanced Dental Students’ Use, Knowledge, and Beliefs Regarding Tobacco Products](https://www.ncbi.nlm.nih.gov/pubmed/29093145)

4.  [Discordant reporting of nonmedical opioid use in a nationally representative sample of US high school seniors. ](https://www.ncbi.nlm.nih.gov/pubmed/27315427)

5.  [Characteristics of Adults Who Switched from Cigarette Smoking to E-cigarettes.](https://www.ncbi.nlm.nih.gov/pubmed/28864130)

***For a full list of references please click [here.](https://orcid.org/0000-0002-3277-9958)***

<br>

## Teaching Experience

* **Teach for America Corps Member, Newark, NJ**  
6/2012-6/2014	
    + Selected from highly competitive pool to join national teacher corps of recent college graduates and professionals who commit two years to teach in high need public schools.

###

* **English and Special Education Teacher**  
Newark BRIDGES High School, Newark Public Schools, Newark, NJ  
8/2012 - 6/2014
    + Consistently commended by supervisor for outstanding teaching and dedication to students at an urban, public, alternative education school serving over-aged and under-credited students   
    + Requested by supervisor to create and deliver over 6 professional development sessions to full school staff  
    + Served as Senior Class Advisor to a class of 100 graduating seniors; including organizing fundraisers, planning Graduation events, and leading student representatives to plan graduation activities and school spirit activities  
    + Awarded Staff of the Month for outstanding service and work ethic
