---
title: 'Problem 2: New York Weather'
output:
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r setup, include=FALSE}

library(tidyverse)
library(flexdashboard)
library(plotly)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))

```


```{r noaa data prep, cache=TRUE}

noaa = p8105.datasets::ny_noaa %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("year", "month", "day"), sep = "-") %>% 
  mutate(tmax = as.numeric(tmax),
         tmin = as.numeric(tmin),
         tmax_c = tmax/10,
         tmin_c = tmin/10,
         prcp_mm = prcp/10,
         snow_cm = snow/10,
         snwd_cm = snwd/10,
         year = as.numeric(year)) %>% 
  select(id, year, month, day, tmax_c, tmin_c, prcp_mm, snow_cm, snwd_cm) %>% 
  filter(id == "USC00303773" | id == "USC00305714" | id == "USW00094794")

```

Row {data-height=700}
-----------------------------------------------------------------------

### Plot 1. Average July Precipitation, 3 New York Locations

```{r plot 1}

noaa %>% 
  filter(month == "07") %>%
  group_by(year, id) %>% 
  summarise(avg_prcp = mean(prcp_mm, na.rm = TRUE),
            avg_tmax = mean(tmax_c, na.rm = TRUE),
            avg_tmin = mean(tmin_c, na.rm = TRUE)) %>% 
  mutate(text_label = str_c("Max Temp: ", avg_tmax, '\nMin Temp: ', avg_tmin)) %>% 
  plot_ly(x = ~year, y = ~avg_prcp, type = "bar",
          alpha = 0.75, 
          color = ~id,
          text = ~text_label)

```


Row {data-height=700}
-----------------------------------------------------------------------

### Plot 2. Maximum Temperature, 1985

```{r}

noaa %>% 
  filter(year == "1985") %>%
  plot_ly(y = ~tmax_c, color = ~id, type = "box")

  
```

### Plot 3. Average Snowfall Over Time

```{r}

noaa %>% 
  group_by(year, id) %>% 
  summarise(avg_sn = mean(snow_cm, na.rm = TRUE)) %>% 
  filter(id == "USC00305714" | id == "USW00094794") %>% 
  plot_ly(y = ~avg_sn, x = ~year, color = ~id, type = "scatter", mode = "markers")


```

