---
title: "Publications"
---
***

## Selected Publications

### Manuscripts in Progress
1.  Effects of exposure to direct and secondhand hookah and e-cigarette aerosols on ambient air quality and cardiopulmonary health in adults and children: protocol for a panel study (Shearston et al., submitted)
2.  Gasoline Vapor Emissions During Vehicle Refueling Events, New York City (Jenni Shearston and Markus Hilpert, in preparation)
3.  Impacts of a Distribution Center on a Community in the South Bronx (in preparation)
4.  Effects of Electronic Cigarettes and Hookah Water Pipe Use on Home Air Quality (Shearston et al., in preparation)

<br>

### Hookah, Electronic Cigarettes, and Cigarettes
1.  Weitzman M, Yusufali AH, Bali F, Vilcassim MJ, Gandhi S, Peltier R, Nadas A, Sherman S, Lee L, Hong Z, **Shearston J**, Park SH, Gordon T. [Effects of hookah smoking on indoor air quality.](https://www.ncbi.nlm.nih.gov/pubmed/27798320) Tob Control. 2016, Oct 26. pii: tobaccocontrol-2016-053165.  

2.  **Shearston JA**, Shah K, Cheng E, Moosvi R, Park SH, Patel N, Spielman AI, Weitzman M. [Dental, Dental Hygiene, and Advanced Dental Students’ Use, Knowledge, and Beliefs Regarding Tobacco Products.](https://www.ncbi.nlm.nih.gov/pubmed/29093145) J Dental Educ. 2017, Nov:81(11):1317-1326. doi: 10.21815/JDE.017.091.  

3.  Park SH, Duncan D, El Shahawy O, Lee L, **Shearston JA**, Tamura K, Sherman SE, Weitzman M. [Characteristics of Adults Who Switched from Cigarette Smoking to E-cigarettes.](https://www.ncbi.nlm.nih.gov/pubmed/28864130) Am J Prev Med. 2017, Aug 22.  pii: S0749-3797(17)30363-X. doi: 10.1016/j.amepre.2017.06.033.  

4.  Cawkwell PB, Lee L, **Shearston J**, Sherman SE, Weitzman M. [The Difference a Decade Makes: Smoking Cessation Counseling and Screening at Pediatric Visits.](https://www.ncbi.nlm.nih.gov/pubmed/27613894) Nicotine Tob Res. 2016, July11. pii: ntw146.  

5.  Park SH, Lee L, **Shearston JA**, Weitzman M. [Patterns of Electronic Cigarette Use and Level of Psychological Distress.](https://www.ncbi.nlm.nih.gov/pubmed/28278239) PLoS ONE. 2017, Mar 9;12(3):e0173625.  
 
<br>

### Opioid Use
1.  Palamar JJ, **Shearston JA**, Cleland CM. [Discordant reporting of nonmedical opioid use in a nationally representative sample of US high school seniors.](https://www.ncbi.nlm.nih.gov/pubmed/27315427) Am J Drug Alcohol Abuse. 2016, Jun 17:1-9.  

2.  Palamar JJ and **Shearston JA**. [Nonmedical Opioid Use in Relation to Recency of Heroin Use in a Nationally Representative Sample of Adults in the United States. ](https://www.ncbi.nlm.nih.gov/pubmed/28895798) J Psychoactive Drugs. 2017, Sep 12:1-8.   

3. Palamar JJ, **Shearston JA**, Dawson EW, Mateu-Gelabert P, Ompad DC. [Nonmedical opioid use and heroin use in a nationally representative sample of US high school seniors.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4698068/) Drug Alcohol Depen. 2016;1(158):132-8.  

<br>
 
####***For a full list of publications please see my ORCID page [here.](https://orcid.org/0000-0002-3277-9958)***

<br>